-- database: aion_world_live
CREATE OR REPLACE FUNCTION gm_guildda_srchguilditem(
    p_guild_id integer,
    p_warehouse integer
) RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT	i.producer, i.tid, i.expired_time, i.buy_amount, i.buy_duration, i.id, i.name_id, i.amount, i.slot, i.warehouse , soul_bound, enchant_count, skin_name_id, stat_enchant_name0, stat_enchant_name1, stat_enchant_name2, stat_enchant_name3, stat_enchant_name4, stat_enchant_name5, option_count, dye_info, proc_tool_nameid, obtain_skin_type, expire_skin_time, expire_dye_time, COALESCE(random_option,0) AS random_option , COALESCE(limit_enchant_count,0) AS limit_enchant_count, COALESCE(reidentify_count,0) AS reidentify_count , COALESCE(freetradestate, 0) as freetradestate , COALESCE(o.authorize_count, 0) as authorize_count, COALESCE(o.vanish_point, 0) as vanish_point , COALESCE(attribute1, 0) as attribute1, COALESCE(attribute1value, 0) as attribute1value, COALESCE(attribute2, 0) as attribute2, COALESCE(attribute2value, 0) as attribute2value, COALESCE(attribute3, 0) as attribute3, COALESCE(attribute3value, 0) as attribute3value, COALESCE(attribute4, 0) as attribute4, COALESCE(attribute4value, 0) as attribute4value, COALESCE(attribute5, 0) as attribute5, COALESCE(attribute5value, 0) as attribute5value, COALESCE(attribute6, 0) as attribute6, COALESCE(attribute6value, 0) as attribute6value , COALESCE(proc_break_count, 0) as proc_break_count, COALESCE(proc_break_flag, 0) as proc_break_flag , COALESCE(exceedState, 0) as exceedState, COALESCE(exceedSkillId1, 0) as exceedSkillId1, COALESCE(exceedSkillId2, 0) as exceedSkillId2, COALESCE(exceedSkillId3, 0) as exceedSkillId3 , COALESCE(baseSkillId, 0) as baseSkillId , COALESCE(enhanceSkillGroup, 0) as enhanceSkillGroup, COALESCE(enhanceSkillLevel, 0) as enhanceSkillLevel , COALESCE(equipLevelDown, 0) as equipLevelDown , COALESCE(wardrobeSlotId, 0) as wardrobeSlotId , COALESCE(randomAttr1, 0) as randomAttr1, COALESCE(randomValue1, 0) as randomValue1, COALESCE(randomAttr2, 0) as randomAttr2, COALESCE(randomValue2, 0) as randomValue2, COALESCE(randomAttr3, 0) as randomAttr3, COALESCE(randomValue3, 0) as randomValue3, COALESCE(randomAttr4, 0) as randomAttr4, COALESCE(randomValue4, 0) as randomValue4, COALESCE(randomAttr5, 0) as randomAttr5, COALESCE(randomValue5, 0) as randomValue5 , COALESCE(randomAttr6, 0) as randomAttr6, COALESCE(randomValue6, 0) as randomValue6, COALESCE(randomAttr7, 0) as randomAttr7, COALESCE(randomValue7, 0) as randomValue7, COALESCE(randomAttr8, 0) as randomAttr8, COALESCE(randomValue8, 0) as randomValue8, COALESCE(randomAttr9, 0) as randomAttr9, COALESCE(randomValue9, 0) as randomValue9, COALESCE(randomAttr10, 0) as randomAttr10, COALESCE(randomValue10, 0) as randomValue10 FROM	guild g , user_item i  LEFT JOIN user_item_option o  ON i.id = o.id and i.char_id = o.char_id LEFT JOIN user_item_freeTrade f  on i.id = f.id LEFT JOIN user_item_attribute a  on i.id = a.id WHERE	g.id = p_guild_id and g.id = i.char_id and (i.warehouse = p_warehouse or i.warehouse = '53');
END;
$$;
