-- database: aion_world_live
CREATE OR REPLACE FUNCTION gm_userdatadao_updatecustomdata(
    p_char_id integer,
    p_race smallint,
    p_gender boolean,
    p_name_id integer,
    p_head_face_color integer,
    p_head_hair_color integer,
    p_head_face_type smallint,
    p_head_hair_type smallint,
    p_head_eye_color integer,
    p_height_scale double precision,
    p_head_feat_type1 smallint,
    p_head_feat_type2 smallint,
    p_feat_face_shape smallint,
    p_feat_forehead_shape smallint,
    p_feat_eye_position smallint,
    p_feat_eye_glabella smallint,
    p_feat_eye_length smallint,
    p_feat_eye_height smallint,
    p_feat_eye_shape smallint,
    p_feat_eye_tail smallint,
    p_feat_eyeblow_pos smallint,
    p_feat_eyeblow_angle smallint,
    p_feat_eyeblow_shape smallint,
    p_feat_nose_pos smallint,
    p_feat_nose_bridge smallint,
    p_feat_nose_side smallint,
    p_feat_nose_tip smallint,
    p_feat_cheek_shape smallint,
    p_feat_mouth_pos smallint,
    p_feat_mouth_size smallint,
    p_feat_lip_thickness smallint,
    p_feat_lip_tail smallint,
    p_feat_lip_shape smallint,
    p_feat_jaw_pos smallint,
    p_feat_jaw_shape smallint,
    p_feat_head_size smallint,
    p_feat_neck_thickness smallint,
    p_feat_neck_length smallint,
    p_feat_shoulder_size smallint,
    p_feat_upper_size smallint,
    p_feat_bust_size smallint,
    p_feat_waist_size smallint,
    p_feat_hip_size smallint,
    p_feat_arm_thickness smallint,
    p_feat_hand_size smallint,
    p_feat_leg_thickness smallint,
    p_feat_foot_size smallint,
    p_feat_wing_size smallint,
    p_feat_version smallint,
    p_feat_ear_shape smallint,
    p_feat_face_ratio smallint,
    p_feat_arm_length smallint,
    p_feat_leg_length smallint,
    p_head_lip_color integer,
    p_feat_shoulder_width smallint,
    p_head_bump_type smallint,
    p_head_expression_type smallint,
    p_feat_head_figure smallint
) RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE	user_data SET race = p_race::integer, gender = (p_gender != 0), name_id = p_name_id, feat_version = p_feat_version, height_scale = p_height_scale, head_hair_type = p_head_hair_type, head_face_type = p_head_face_type, head_feat_type1 = p_head_feat_type1, head_feat_type2 = p_head_feat_type2, head_bump_type = p_head_bump_type, head_expression_type = p_head_expression_type, head_hair_color = p_head_hair_color, head_lip_color = p_head_lip_color, head_eye_color = p_head_eye_color, head_face_color = p_head_face_color, feat_face_shape = p_feat_face_shape, feat_forehead_shape = p_feat_forehead_shape, feat_eye_position = p_feat_eye_position, feat_eye_glabella = p_feat_eye_glabella, feat_eye_length = p_feat_eye_length, feat_eye_height = p_feat_eye_height, feat_eye_shape = p_feat_eye_shape, feat_eye_tail = p_feat_eye_tail, feat_eyeblow_pos = p_feat_eyeblow_pos, feat_eyeblow_angle = p_feat_eyeblow_angle, feat_eyeblow_shape = p_feat_eyeblow_shape, feat_nose_pos = p_feat_nose_pos, feat_nose_bridge = p_feat_nose_bridge, feat_nose_side = p_feat_nose_side, feat_nose_tip = p_feat_nose_tip, feat_cheek_shape = p_feat_cheek_shape, feat_mouth_pos = p_feat_mouth_pos, feat_mouth_size = p_feat_mouth_size, feat_lip_thickness = p_feat_lip_thickness, feat_lip_tail = p_feat_lip_tail, feat_lip_shape = p_feat_lip_shape, feat_jaw_pos = p_feat_jaw_pos, feat_jaw_shape = p_feat_jaw_shape, feat_ear_shape = p_feat_ear_shape, feat_head_size = p_feat_head_size, feat_neck_thickness = p_feat_neck_thickness, feat_neck_length = p_feat_neck_length, feat_shoulder_size = p_feat_shoulder_size, feat_upper_size = p_feat_upper_size, feat_bust_size = p_feat_bust_size, feat_waist_size = p_feat_waist_size, feat_hip_size = p_feat_hip_size, feat_arm_thickness = p_feat_arm_thickness, feat_hand_size = p_feat_hand_size, feat_leg_thickness = p_feat_leg_thickness, feat_foot_size = p_feat_foot_size, feat_face_ratio = p_feat_face_ratio, feat_wing_size = p_feat_wing_size, feat_arm_length = p_feat_arm_length, feat_leg_length = p_feat_leg_length, feat_shoulder_width = p_feat_shoulder_width, feat_head_figure = p_feat_head_figure WHERE	char_id = p_char_id::integer;
END;
$$;
