-- AionCore 5.8 — Sprint 1.1a Round 5 (Track B3) PvE scaffold round 2.
--
-- Extends 00002_pve_scaffold.sql to satisfy the schema surface required by
-- the 18-SP Round 5 batch (login → enter world → kill mob → loot → exp →
-- save → logout). As before this is NOT the full 1063-SP AionWorldLive
-- schema — only the columns the ported SPs actually touch. Round 6+ will
-- extend further as auction/abyss/PvP SPs come online.
--
-- New tables (NCSoft column names + types preserved):
--   user_item              — character inventory (PutItem / GetItem / SetItemAmount / DeleteItem)
--   user_item_option       — sister table of user_item (per-row enchant/skin/option flags)
--   user_item_charge       — purely for DeleteItem cascade
--   user_item_polish       — purely for DeleteItem cascade
--   user_item_attribute    — purely for DeleteItem cascade
--   user_skill             — known skills + skill_data (PutSkill / GetSkillList)
--   user_skill_cooltime    — per-skill cooldown persistence (PutSkillCooltime / GetSkillCooltime)
--   user_skill_skin        — cosmetic skin (PutSkillSkin)
--   user_quest             — quest progress per char (PutQuest / GetQuestList)
--   user_instance          — instance entry / lock per char (Get/Set/InitInstance)
--   instance               — instance metadata (validity_time joined by GetUserInstance)
--   user_mail              — mail inbox (MailWriteSys + Mail* family)
--   forbidden_word         — name validation (CheckValidCharName + PutGuild)
--   forbidden_char         — char-name reservation (CheckValidCharName)
--
-- Extended user_data columns:
--   guild_rank, guild_intro          — needed by SetGuildMember/Rank, DeleteGuildMemberAll
--   user_id, account_name            — needed by CheckValidCharName / GetCharIdList
--   delete_date defaults preserved
--   cur_server, world, xlocation, ylocation, zlocation, dir   — char location SPs
--   last_login_time, last_logout_time, playtime               — login/logout time
--   cp                               — SetCharCP
--   rank_point                       — AddCharRankPoint
--
-- IDENTITY semantics: NCSoft used IDENTITY(1,1) on user_data.char_id,
-- guild.id, user_item.id, user_mail.id. PG equivalent is GENERATED BY
-- DEFAULT AS IDENTITY — already INTEGER PK in 00002 so we add a sequence
-- helper for new rows that omit the id (via NEXTVAL trigger when needed).
-- For Round 5 we keep PUT SPs accepting char_id as input (caller assigns)
-- and only use IDENTITY on user_item / user_mail / guild where T-SQL did.

-- +goose Up

-- +goose StatementBegin
-- Extend user_data with the columns the Round 5 SP batch reads/writes.
ALTER TABLE user_data
    ADD COLUMN IF NOT EXISTS user_id          TEXT        NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS account_name     TEXT        NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS guild_rank       INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS guild_intro      TEXT        NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cur_server       INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS world            INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS xlocation        REAL        NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ylocation        REAL        NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS zlocation        REAL        NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dir              INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_login_time  TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    ADD COLUMN IF NOT EXISTS last_logout_time TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    ADD COLUMN IF NOT EXISTS playtime         INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cp               INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rank_point       BIGINT      NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lev              INTEGER     NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS exp              BIGINT      NOT NULL DEFAULT 0;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_data_account ON user_data(account_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_data_user_id ON user_data(user_id);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_item — primary inventory row (PutItem inserts here; GetItem joins to _option)
CREATE TABLE IF NOT EXISTS user_item (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    char_id            INTEGER     NOT NULL,
    name_id            INTEGER     NOT NULL DEFAULT 0,
    slot_id            INTEGER     NOT NULL DEFAULT 0,
    amount             BIGINT      NOT NULL DEFAULT 0,
    tid                BIGINT      NOT NULL DEFAULT 0,
    slot               INTEGER     NOT NULL DEFAULT 0,
    warehouse          INTEGER     NOT NULL DEFAULT 0,
    producer           TEXT        NOT NULL DEFAULT '',
    expired_time       INTEGER     NOT NULL DEFAULT 0,
    buy_amount         INTEGER     NOT NULL DEFAULT 0,
    buy_duration       INTEGER     NOT NULL DEFAULT 0,
    dynamic_property   INTEGER     NOT NULL DEFAULT 0,
    server_of_origin   INTEGER     NOT NULL DEFAULT 0,
    soul_bound         INTEGER     NOT NULL DEFAULT 0,
    enchant_count      INTEGER     NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_item_char ON user_item(char_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_item_tid ON user_item(tid);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_item_option — sister table for cosmetics + enchant + dye + skill exceed
CREATE TABLE IF NOT EXISTS user_item_option (
    id                     BIGINT  PRIMARY KEY REFERENCES user_item(id) ON DELETE CASCADE,
    char_id                INTEGER NOT NULL,
    soul_bound             INTEGER NOT NULL DEFAULT 0,
    enchant_count          INTEGER NOT NULL DEFAULT 0,
    skin_name_id           INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name0     INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name1     INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name2     INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name3     INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name4     INTEGER NOT NULL DEFAULT 0,
    stat_enchant_name5     INTEGER NOT NULL DEFAULT 0,
    option_count           INTEGER NOT NULL DEFAULT 0,
    dye_info               INTEGER NOT NULL DEFAULT 0,
    proc_tool_nameid       INTEGER NOT NULL DEFAULT 0,
    obtain_skin_type       INTEGER NOT NULL DEFAULT 0,
    expire_skin_time       INTEGER NOT NULL DEFAULT 0,
    expire_dye_time        INTEGER NOT NULL DEFAULT 0,
    random_option          INTEGER NOT NULL DEFAULT 0,
    limit_enchant_count    INTEGER NOT NULL DEFAULT 0,
    reidentify_count       INTEGER NOT NULL DEFAULT 0,
    authorize_count        INTEGER NOT NULL DEFAULT 0,
    vanish_point           INTEGER NOT NULL DEFAULT 0,
    enchant_prob_addition  INTEGER NOT NULL DEFAULT 0,
    option_prob_addition   INTEGER NOT NULL DEFAULT 0,
    KeyNameId              INTEGER NOT NULL DEFAULT 0,
    exceedState            INTEGER NOT NULL DEFAULT 0,
    ExceedSkillId1         INTEGER NOT NULL DEFAULT 0,
    ExceedSkillId2         INTEGER NOT NULL DEFAULT 0,
    ExceedSkillId3         INTEGER NOT NULL DEFAULT 0,
    BaseSkillId            INTEGER NOT NULL DEFAULT 0,
    enhanceSkillGroup      INTEGER NOT NULL DEFAULT 0,
    enhanceSkillLevel      INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_item_charge / _polish / _attribute exist purely so DeleteItem cascade
-- DELETE doesn't error. Schema is intentionally minimal — Round 6+ will
-- expand when SetItemPolish / SetItemChargePoint are ported.
CREATE TABLE IF NOT EXISTS user_item_charge (
    id BIGINT PRIMARY KEY REFERENCES user_item(id) ON DELETE CASCADE,
    charge_point INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_item_polish (
    id BIGINT PRIMARY KEY REFERENCES user_item(id) ON DELETE CASCADE,
    polish_info INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_item_attribute (
    id BIGINT PRIMARY KEY REFERENCES user_item(id) ON DELETE CASCADE,
    attribute INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_skill — known skills per char. PutSkill upserts (char_id, skill_id).
CREATE TABLE IF NOT EXISTS user_skill (
    char_id     INTEGER NOT NULL,
    skill_id    INTEGER NOT NULL,
    skill_data1 INTEGER NOT NULL DEFAULT 0,
    skill_data2 INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (char_id, skill_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_skill_cooltime — per-skill cooldown persistence on logout for combat safety
CREATE TABLE IF NOT EXISTS user_skill_cooltime (
    char_id     INTEGER NOT NULL,
    skill_id    INTEGER NOT NULL,
    use_time    INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (char_id, skill_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_skill_skin — cosmetic skin per skill (item-shop)
CREATE TABLE IF NOT EXISTS user_skill_skin (
    char_id      INTEGER NOT NULL,
    skill_id     INTEGER NOT NULL,
    skill_skin   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (char_id, skill_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_quest — quest state per char. PutQuest INSERTs; SetQuest (Round 6) UPDATEs.
CREATE TABLE IF NOT EXISTS user_quest (
    char_id        INTEGER NOT NULL,
    quest_id       INTEGER NOT NULL,
    quest_status   INTEGER NOT NULL DEFAULT 0,
    quest_progress INTEGER NOT NULL DEFAULT 0,
    quest_branch   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (char_id, quest_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
-- instance — server-side instance metadata (validity_time joined into GetUserInstance)
CREATE TABLE IF NOT EXISTS instance (
    instance_id   INTEGER PRIMARY KEY,
    validity_time INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_instance — per-char instance entry/cooldown. Composite key (char_id, world_id).
CREATE TABLE IF NOT EXISTS user_instance (
    char_id          INTEGER NOT NULL,
    world_id         INTEGER NOT NULL,
    instance_id      INTEGER NOT NULL DEFAULT 0,
    reentrance_time  INTEGER NOT NULL DEFAULT 0,
    server_id        INTEGER NOT NULL DEFAULT 0,
    count_variate    INTEGER NOT NULL DEFAULT 0,
    kina_increase    INTEGER NOT NULL DEFAULT 0,
    item_increase    INTEGER NOT NULL DEFAULT 0,
    spinel_increase  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (char_id, world_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
-- user_mail — mail inbox row (MailWriteSys inserts; MailList/MailRead/MailDelete update)
CREATE TABLE IF NOT EXISTS user_mail (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_id         INTEGER NOT NULL,
    to_name       TEXT    NOT NULL DEFAULT '',
    from_id       INTEGER NOT NULL,
    from_name     TEXT    NOT NULL DEFAULT '',
    title         TEXT    NOT NULL DEFAULT '',
    content       TEXT    NOT NULL DEFAULT '',
    item_id       BIGINT  NOT NULL DEFAULT 0,
    item_nameid   INTEGER NOT NULL DEFAULT 0,
    item_amount   BIGINT  NOT NULL DEFAULT 0,
    money         BIGINT  NOT NULL DEFAULT 0,
    arrive_time   INTEGER NOT NULL DEFAULT 0,
    express_mail  INTEGER NOT NULL DEFAULT 0,
    is_read       INTEGER NOT NULL DEFAULT 0,
    delete_flag   INTEGER NOT NULL DEFAULT 0
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_mail_to ON user_mail(to_id) WHERE delete_flag = 0;
-- +goose StatementEnd

-- +goose StatementBegin
-- forbidden_word — name validation lookup. forbidden_type/0=common,1=char,2=guild.
CREATE TABLE IF NOT EXISTS forbidden_word (
    forbidden_id     SERIAL  PRIMARY KEY,
    forbidden_word   TEXT    NOT NULL,
    forbidden_type   INTEGER NOT NULL DEFAULT 0,
    forbidden_reason INTEGER NOT NULL DEFAULT 1,
    is_like          INTEGER NOT NULL DEFAULT 0,
    status           INTEGER NOT NULL DEFAULT 0,
    regdate          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_forbidden_word_word ON forbidden_word(forbidden_word) WHERE status = 0;
-- +goose StatementEnd

-- +goose StatementBegin
-- forbidden_char — per-char name reservation (server transfer / item rename)
CREATE TABLE IF NOT EXISTS forbidden_char (
    forbidden_id          SERIAL  PRIMARY KEY,
    forbidden_char        TEXT    NOT NULL,
    forbidden_account_nm  TEXT    NOT NULL DEFAULT '',
    forbidden_reason      INTEGER NOT NULL DEFAULT 0,
    status                INTEGER NOT NULL DEFAULT 0,
    regdate               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_forbidden_char_name ON forbidden_char(forbidden_char) WHERE status = 0;
-- +goose StatementEnd

-- +goose Down

-- +goose StatementBegin
DROP INDEX IF EXISTS idx_forbidden_char_name;
DROP INDEX IF EXISTS idx_forbidden_word_word;
DROP INDEX IF EXISTS idx_user_mail_to;
DROP INDEX IF EXISTS idx_user_item_tid;
DROP INDEX IF EXISTS idx_user_item_char;
DROP INDEX IF EXISTS idx_user_data_user_id;
DROP INDEX IF EXISTS idx_user_data_account;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE IF EXISTS forbidden_char;
DROP TABLE IF EXISTS forbidden_word;
DROP TABLE IF EXISTS user_mail;
DROP TABLE IF EXISTS user_instance;
DROP TABLE IF EXISTS instance;
DROP TABLE IF EXISTS user_quest;
DROP TABLE IF EXISTS user_skill_skin;
DROP TABLE IF EXISTS user_skill_cooltime;
DROP TABLE IF EXISTS user_skill;
DROP TABLE IF EXISTS user_item_attribute;
DROP TABLE IF EXISTS user_item_polish;
DROP TABLE IF EXISTS user_item_charge;
DROP TABLE IF EXISTS user_item_option;
DROP TABLE IF EXISTS user_item;
-- +goose StatementEnd

-- +goose StatementBegin
-- ALTER ... DROP COLUMN IF EXISTS for the user_data extensions
ALTER TABLE user_data
    DROP COLUMN IF EXISTS exp,
    DROP COLUMN IF EXISTS lev,
    DROP COLUMN IF EXISTS rank_point,
    DROP COLUMN IF EXISTS cp,
    DROP COLUMN IF EXISTS playtime,
    DROP COLUMN IF EXISTS last_logout_time,
    DROP COLUMN IF EXISTS last_login_time,
    DROP COLUMN IF EXISTS dir,
    DROP COLUMN IF EXISTS zlocation,
    DROP COLUMN IF EXISTS ylocation,
    DROP COLUMN IF EXISTS xlocation,
    DROP COLUMN IF EXISTS world,
    DROP COLUMN IF EXISTS cur_server,
    DROP COLUMN IF EXISTS guild_intro,
    DROP COLUMN IF EXISTS guild_rank,
    DROP COLUMN IF EXISTS account_name,
    DROP COLUMN IF EXISTS user_id;
-- +goose StatementEnd
