-- AionCore 5.8 — Sprint 1.1a batch 3 port: aion_AddOfflineBuddy.
--
-- Source: ai/wiki/raw/47104-sp-dump/AionWorldLive/procedures/aion_AddOfflineBuddy.sql
--
-- Original (T-SQL) — paraphrased:
--   if (charid, inviterId) row already in user_buddy_offline    → return 12  (already pending in)
--   if (inviterId, charId) row already in user_buddy_offline    → return 19  (already pending out)
--   if charId's total buddy count (active + pending + cross-server) >= 100  → return 14  (invitee full)
--   if inviterId's total buddy count >= 100                      → return 13  (inviter full)
--   else INSERT user_buddy_offline(...) and return 11           (queued; SM_ASK_BUDDY when invitee logs in)
--
-- Schema delta:
--   * user_buddy_offline — pending-invite queue. Created here. NCSoft column
--     names mirrored 1:1 so future ports (aion_GetOfflineBuddyList,
--     aion_DeleteOfflineBuddy) can be byte-for-byte ports.
--   * user_buddy_inter — cross-server buddy roster (served by ChannelServer
--     in NCSoft). We provision the table empty so the count math works out;
--     the actual cross-server fill path is part of the chat/director shard
--     (deferred to Q2). Today every char has 0 inter rows so the predicate
--     reduces to "active + pending < 100", which matches NCSoft's effective
--     single-server behaviour during early game.
--
-- Translation notes:
--   * NCSoft `with(nolock)` hint is dropped — PG MVCC gives non-blocking reads
--     for free, and a dirty-read here would actually be wrong (we'd let two
--     concurrent invites both squeeze past the 100-cap).
--   * Cap value is 100 (not 200 like aion_AnswerOfflineBuddy uses for the
--     ACTIVE buddy ceiling) — this is the deliberate NCSoft asymmetry: the
--     pending+active sum is harder-capped to keep the inbox bounded, while
--     mutually-confirmed friendships can grow to 200.
--   * Return codes are the legacy numeric protocol that maps directly to the
--     SM_BUDDY_RESPONSE op-payload byte; preserved verbatim.

-- +goose Up

-- +goose StatementBegin
-- Pending offline-buddy invite queue. Each row: invitee = user_id; inviter
-- supplies the metadata we'll need to render the SM_ASK_BUDDY popup when
-- the invitee logs in (level / class / gender + a 256-char message).
CREATE TABLE IF NOT EXISTS user_buddy_offline (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER     NOT NULL,
    inviter_id    INTEGER     NOT NULL,
    inviter_name  TEXT        NOT NULL DEFAULT '',
    inviter_msg   TEXT        NOT NULL DEFAULT '',
    createdate    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    userlevel     INTEGER     NOT NULL DEFAULT 0,
    userclass     INTEGER     NOT NULL DEFAULT 0,
    gender        INTEGER     NOT NULL DEFAULT 0,
    UNIQUE (user_id, inviter_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_buddy_offline_user    ON user_buddy_offline(user_id);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_user_buddy_offline_inviter ON user_buddy_offline(inviter_id);
-- +goose StatementEnd

-- +goose StatementBegin
-- Cross-server buddy roster — empty for now (no cross-server chat shard).
-- The count predicate in aion_AddOfflineBuddy reads from this table so the
-- table must exist; an empty table simply contributes 0 to the count.
CREATE TABLE IF NOT EXISTS user_buddy_inter (
    char_id      INTEGER NOT NULL,
    buddy_id     INTEGER NOT NULL,
    delete_flag  INTEGER NOT NULL DEFAULT 0,
    buddy_name   TEXT    NOT NULL DEFAULT '',
    server_id    INTEGER NOT NULL DEFAULT 0,
    comment      TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (char_id, buddy_id, server_id)
);
-- +goose StatementEnd

-- +goose StatementBegin
DROP FUNCTION IF EXISTS aion_add_offline_buddy(INTEGER, INTEGER, TEXT, TEXT, INTEGER, INTEGER, INTEGER);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION aion_add_offline_buddy(
    _char_id      INTEGER,
    _inviter_id   INTEGER,
    _inviter_name TEXT,
    _message      TEXT,
    _level        INTEGER,
    _class        INTEGER,
    _gender       INTEGER
)
RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    buddy_count INTEGER;
    off_count   INTEGER;
    inter_count INTEGER;
BEGIN
    -- (1) Already-pending cases (NCSoft: 12 inbound dup, 19 outbound dup)
    IF EXISTS (SELECT 1 FROM user_buddy_offline
                WHERE user_id = _char_id AND inviter_id = _inviter_id) THEN
        RETURN 12;
    END IF;

    IF EXISTS (SELECT 1 FROM user_buddy_offline
                WHERE user_id = _inviter_id AND inviter_id = _char_id) THEN
        RETURN 19;
    END IF;

    -- (2) Invitee's combined ceiling (active + pending + inter).
    SELECT COUNT(*) INTO buddy_count FROM user_buddy_list WHERE char_id  = _char_id;
    SELECT COUNT(*) INTO off_count   FROM user_buddy_offline WHERE user_id = _char_id;
    SELECT COUNT(*) INTO inter_count FROM user_buddy_inter   WHERE char_id  = _char_id;
    IF (buddy_count + off_count + inter_count) >= 100 THEN
        RETURN 14;
    END IF;

    -- (3) Inviter's combined ceiling.
    SELECT COUNT(*) INTO buddy_count FROM user_buddy_list   WHERE char_id    = _inviter_id;
    SELECT COUNT(*) INTO off_count   FROM user_buddy_offline WHERE inviter_id = _inviter_id;
    SELECT COUNT(*) INTO inter_count FROM user_buddy_inter   WHERE char_id    = _inviter_id;
    IF (buddy_count + off_count + inter_count) >= 100 THEN
        RETURN 13;
    END IF;

    -- (4) Queue the invite. UNIQUE (user_id, inviter_id) makes the dup-check
    --     above redundant under serialised execution, but the explicit code
    --     paths keep the return codes legible.
    INSERT INTO user_buddy_offline
        (user_id, inviter_id, inviter_name, inviter_msg, userlevel, userclass, gender)
    VALUES
        (_char_id, _inviter_id, _inviter_name, _message, _level, _class, _gender);

    RETURN 11;
END;
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP FUNCTION IF EXISTS aion_add_offline_buddy(INTEGER, INTEGER, TEXT, TEXT, INTEGER, INTEGER, INTEGER);
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE IF EXISTS user_buddy_inter;
-- +goose StatementEnd

-- +goose StatementBegin
DROP INDEX IF EXISTS idx_user_buddy_offline_inviter;
-- +goose StatementEnd

-- +goose StatementBegin
DROP INDEX IF EXISTS idx_user_buddy_offline_user;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE IF EXISTS user_buddy_offline;
-- +goose StatementEnd
