-- AionCore 5.8 — Sprint 1.1a batch 12 port: aion_PutGuildHistory.
--
-- Source: ai/wiki/raw/47104-sp-dump/AionWorldLive/procedures/aion_PutGuildHistory.sql
-- Original (T-SQL):
--   INSERT guild_history(guild_id, eventDate, eventType, eventParam, eventParam2)
--   VALUES (@nGuildId, @nEventDate, @nEventType, @nEventParam, @nEventParam2)
--
-- Translation notes:
--   * `guild_history` is the legion's audit log — every join/leave/promote/
--     emblem-change/notice-change/dispers/rename/etc. event is appended.
--     There is no UNIQUE / no upsert behaviour: history is append-only.
--   * `eventType` is `tinyint` in T-SQL (0..255) → SMALLINT in PG (PG has
--     no native unsigned 8-bit; SMALLINT covers the range losslessly).
--   * `eventParam` / `eventParam2` are `nvarchar(32)` (string descriptors,
--     e.g. char name, item id, before/after value) → TEXT (no length cap;
--     gateway truncates to 32 wide chars on the protocol side).
--   * `eventDate` is INT (epoch seconds; matches NCSoft helper output).
--   * Created here as the first consumer in the SP catalogue; later
--     ports of GetGuildHistoryList / DeleteGuildHistory will reuse this
--     shape. Index on (guild_id, eventDate DESC) for the typical
--     "show me legion N's last 50 events" read pattern.
--   * Returns rows-affected (always 1 for a successful insert).
--
-- Used by:
--   scripts/handlers/cm_legion_*_set.lua    -- emit on every legion event
--   scripts/lib/guild.lua

-- +goose Up
-- +goose StatementBegin
-- ====================================================================
-- guild_history — append-only legion audit log. No FK to `guild` because
-- T-SQL has no FK either, and we want history to survive guild deletion
-- for forensics. Caller is responsible for guild_id integrity.
-- ====================================================================
CREATE TABLE IF NOT EXISTS guild_history (
    id            BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id      INTEGER  NOT NULL,
    event_date    INTEGER  NOT NULL,
    event_type    SMALLINT NOT NULL,
    event_param   TEXT     NOT NULL DEFAULT '',
    event_param2  TEXT     NOT NULL DEFAULT ''
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE INDEX IF NOT EXISTS idx_guild_history_guild
    ON guild_history(guild_id, event_date DESC);
-- +goose StatementEnd

-- +goose StatementBegin
DROP FUNCTION IF EXISTS aion_putguildhistory(INTEGER, INTEGER, SMALLINT, TEXT, TEXT);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION aion_putguildhistory(
    _guild_id      INTEGER,
    _event_date    INTEGER,
    _event_type    SMALLINT,
    _event_param   TEXT,
    _event_param2  TEXT
) RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    affected_cnt INTEGER;
BEGIN
    INSERT INTO guild_history (guild_id, event_date, event_type, event_param, event_param2)
    VALUES (_guild_id, _event_date, _event_type, _event_param, _event_param2);
    GET DIAGNOSTICS affected_cnt = ROW_COUNT;
    RETURN affected_cnt;
END;
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP FUNCTION IF EXISTS aion_putguildhistory(INTEGER, INTEGER, SMALLINT, TEXT, TEXT);
-- +goose StatementEnd

-- +goose StatementBegin
DROP INDEX IF EXISTS idx_guild_history_guild;
-- +goose StatementEnd

-- +goose StatementBegin
DROP TABLE IF EXISTS guild_history;
-- +goose StatementEnd
